apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:5YP97qD7O2Hk7DfxiCS8Vj9LoZOcjz6KCqOeqBQP5ZIRW2R2LDU6PEt8yMPTbhp5BxV1YTmfkEHaSBDohqhXWOZUktmHUUhqIrH6JxR/R0+oPK5cXKkwjBnBMA/o6c1Ej1JhSd6HBxP+xp9PH15ptjMsXEG4ejuZG/MWOkHfXfSTdxt/d55aQzmKiNhyYNsWlJtWyN4vzsCraGKLyKv8ya0UgGqa1wR9+ZgnTv0ah//3/JfMwNnrRIfxRN0XHkj6vQw+ar9dXR2zGAIzjIbpR3seo/RCGyAMZeS7FnnW5fP3Zo8WIjPuOVDpUJ0=,iv:Jh6aHp+8cq+AEiJaQ6Ch8XYgfTNB2T83wgb2kSj2Iig=,tag:XBqVEpiVs0vh3u0ZSEUEqA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdEhBTkJlaVE2YVNLRTV5
            V0VSY2dVai8zTFFxVVVnNUt4L0dBeUhDLzI0CjQyem04bFVzKzRlRXJ3Ykg4ZjJ3
            OSswUEFhQ3JFWWZqa2VZU25sOFhNT0kKLS0tIFNtckZEaW9TYmRPbEQ2aDhmQUtF
            VE5WWFdjZTM0L0Z0b0doUlpZdFp5Um8KKfR808bsbC5G5PPQERLy5O+R6d64ibdM
            Le88smFNnHGa9xOxWfhiIQFCKCOBryXGuy3801TsVsUBHeC3ndz+vQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vy6sjyewf72s4ptls4cd2cksm3zyj842ykcnqfpntmruvhyntf6q0mnf93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T09:31:17Z"
    mac: ENC[AES256_GCM,data:E1oQheqxFnfVjBty1s1Sel+H/naWukZW4I82uKiRa9fF2Oa+6jgUwYs4OmjdDS+qUYbcm2dhvMuEFdrTGHU7SBurW3ZClxUeuPJLemXgH4DAthPZ2Cguz8px3UUeKJvGT0SyYboUuehU9iB4QgFT9HEe27/5+WDY9dejjrYIKr4=,iv:KA2w31KEK+cfp6fFbgS1DkN7Yq6lHypa5Ryk/oMvmBE=,tag:9z4Tr+LE6L7+WcyZTL3zvA==,type:str]
    version: 3.13.2
