apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:2EmRw/jJe6R0AVxvYWT0ALT+PnuL7/GompkxmsFHW5dMK4he1/LdJu2g6ojOI9UP/v4X9jo9Ys4cWtC3PgSfQBi2TuEO2f3CzmmfNpiTU81WVzmlO+R7Nq2DXKVn80TWpFdoxHmGYaTmPp4/tZ02erro8QQYg3qir9AWU4YC+Uaoz8Eh+wE2s22WT3UE1Hgz+VJmjg37OW/JHyBSGkCMHW1gZdC2KcTXcL1r4sidpiNH7jAnyOFrCQXVrcnqzN/Ck3wmHUUgrT7hbBvmgudad+AwIlGxv6jTN1vZ9S76i5J1zULSrg3NTQetDAY=,iv:SCAXyF5yaJTA1/4aG5/fJA5zf1bJrc9Ygh5ugP2lT9c=,tag:19iDyQ+GULFPphLmm18loQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYS96ZDI5NkkrSVk4Y0xm
            RThhRnBJTk10U0hnVkRHZklNeWd2VmFEckhVClp3TWFyR0hsMHA0ak9ZaWc2SWJy
            QXdwOE5GdFphQ2w5dDc5UmdwbTNGdVEKLS0tIHQ3OHdIQm9ZQVFqUTlHeGdmeVRK
            SnZMeXh2d2JKV1pxSFBGMC9qdENNWVEKIF9P0cXd6p6PlHhB2OIyTssUzsNoTTiY
            CqBvxIZ7kbeFOZn/5fMkeHUFEk1d9o68DTn7q49zIR8rSQGvRToEmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vy6sjyewf72s4ptls4cd2cksm3zyj842ykcnqfpntmruvhyntf6q0mnf93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T09:55:01Z"
    mac: ENC[AES256_GCM,data:s1594uDJ6Uik9cWuwqvQnOK7FkrDzub0sjUAqULAUuwOiOi8yFVYtnaCpldKqkKimYRNNcwbHicvxr/wEysMqlbFJzuMWJbnYC7TxQiOnoP7MvegBv/Epe8Vex2/ws4w6+QnuJy5auCyngEmpDAPpSoZ1UP1gUVOkwvO+en66nM=,iv:fRju+spErsObjetL/UNrzBJXlEkKmlg5pgEKcKluHaI=,tag:ClZJDGuB33o3e8BCa76BDQ==,type:str]
    version: 3.13.1
