apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:EOWqxaGnzqA=,iv:ArU1DWOwNRn3gRonJ9OK9MBmJFpXQgE39nzjB8VL/bw=,tag:5yj5UDGa/ZnNrg2PajXTTw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:kcC64mLkvnhuLxU8,iv:5XUyv8UUlRQdzTmdkT/YOh0g5D91ubH/ozXCVyhWQxI=,tag:kQnOgqnTF4KQ5Gx12UlKlQ==,type:str]
kind: Secret
metadata:
    name: creds-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1L0tpeXNyM0RYSG9rVGZK
            RWsvNkdLNVJ1LzlhZ1dISklRQnJIamdGblFFCng3YkI0V1hHZnBsQUtrTlhHK2oz
            VUdEQy9FMXF0MGUzMlVTM1BtSHc2M2sKLS0tIFJCN0h5bHBDN2w1Y1dJd3VmMDdG
            dFNNd2I5NWE1SU9peGJrWG9mSG44YVEKPYQ4oJQVuQx79S4wdlSApOytRoTJIJ5F
            U3Ow+zcjqdtP/kQzXXzUUvZphmrf3H+cBtd3pZ1FSYZhu3SUlomAnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vy6sjyewf72s4ptls4cd2cksm3zyj842ykcnqfpntmruvhyntf6q0mnf93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T09:38:27Z"
    mac: ENC[AES256_GCM,data:I6qF3g6J9MqdRdVlL36JNRUCKIC8lDMwXxWTsbKtD248PqAhaicu7pHmXYS1IVDj/AgLXM4DcDM+oPPPjqb5VOBwYKSuKbZp2nejI3vpzqOQUDF/hdLgRu0YBCd3SXzp5eoQWFWCuyIx/M1UfTzIWHntmSXj8y9oY+hfiTou8MI=,iv:Uw/9FAhHasnBcXHUDkbT6oGiddqsm5PhNmaCYbfQcSg=,tag:x5deBqJVcxL9y0oOstR8GA==,type:str]
    version: 3.13.1
