apiVersion: v1
data:
    password: ENC[AES256_GCM,data:AsbFy3SYnDo=,iv:a0e5eDV89ytIDjgbIgrncoo39iNXwRcoCz+K9k21gR8=,tag:x5J4uht6BvcGULm0/jJ0aQ==,type:str]
    user: ENC[AES256_GCM,data:6moIOEZ/sHY=,iv:ESKUEuOoOA7bQXzKJIULzLJjpRJPmarjOif6OxEu2gQ=,tag:WAOReWBf1WTrMuMKvxfe4w==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcW1uYTM0NXhkNTFwai8z
            d3FWSUFiaUpRS2RwNlkvM1l2b3ZsRDFGNmpnCmdiUTNidmYxandKbUlBSXl0M2VJ
            dVI0Q09hSlN5N2VNS3V1N2FqcEhSL0EKLS0tIG50dEYzNms4TDVBalZFZXhPeXZy
            NFVZZzVQeG00bVJ4K3Jla3hOa2haWUEKc0L+Tf/oINzm5c94KDiEFbLYYNWYTago
            ZHG48atwsksjeuZ1tJ5utwleIkAo61LwgOSmKp5FbDokGUQStyT6Lg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vy6sjyewf72s4ptls4cd2cksm3zyj842ykcnqfpntmruvhyntf6q0mnf93
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T06:57:40Z"
    mac: ENC[AES256_GCM,data:ggCkCpP01lGCcDu5a5EIX/yZS0FPfwEtfDmmqPOGoKv8eQgYODEp3AuunTKuiiTYUadYlkXF3xnh/Qk4f05pkEjUd/fI26P+lQHaAJMYQAA2gBrI3cIzHJGfp/iOpavuJmXrUEUiJX5gKDLIa7RAMNB/2rX466ZqGy0liQmMZzQ=,iv:cy0tVnLUOdtOrp+y/ew+6oTj5PKuyGnljmGgMDOphN4=,tag:ncjIbi2pdygWl6V9tr+/yg==,type:str]
    version: 3.13.1
